# Generated by Django 3.2.7 on 2021-10-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('materials', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='toys/templates/static/img')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
