# Generated by Django 3.2.7 on 2021-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='toy',
            name='materials',
        ),
        migrations.AddField(
            model_name='toy',
            name='materials',
            field=models.ManyToManyField(related_name='toys', to='toys.Material'),
        ),
    ]
