# Generated by Django 3.2.7 on 2021-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20211024_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='image',
            field=models.FilePathField(path='toys/static/img'),
        ),
    ]
